// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLg-6WEk1MdiXYxT3eX9qgFezB7kmm0-U',
    appId: '1:317224688119:web:e23d037357f37e9897b6f2',
    messagingSenderId: '317224688119',
    projectId: 'curelink-3f36f',
    authDomain: 'curelink-3f36f.firebaseapp.com',
    storageBucket: 'curelink-3f36f.firebasestorage.app',
    measurementId: 'G-83BBK6888D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvDsg5CvFQUolus8oECBM8NVumBm87UlY',
    appId: '1:317224688119:android:7dd80f2d3300bdc197b6f2',
    messagingSenderId: '317224688119',
    projectId: 'curelink-3f36f',
    storageBucket: 'curelink-3f36f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYz39chCbUw0sO7GSkGBzNEEALjcUwRg4',
    appId: '1:317224688119:ios:d8c7f69d44c86e3297b6f2',
    messagingSenderId: '317224688119',
    projectId: 'curelink-3f36f',
    storageBucket: 'curelink-3f36f.firebasestorage.app',
    iosBundleId: 'com.example.curelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYz39chCbUw0sO7GSkGBzNEEALjcUwRg4',
    appId: '1:317224688119:ios:d8c7f69d44c86e3297b6f2',
    messagingSenderId: '317224688119',
    projectId: 'curelink-3f36f',
    storageBucket: 'curelink-3f36f.firebasestorage.app',
    iosBundleId: 'com.example.curelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLg-6WEk1MdiXYxT3eX9qgFezB7kmm0-U',
    appId: '1:317224688119:web:61d7767bd12b506f97b6f2',
    messagingSenderId: '317224688119',
    projectId: 'curelink-3f36f',
    authDomain: 'curelink-3f36f.firebaseapp.com',
    storageBucket: 'curelink-3f36f.firebasestorage.app',
    measurementId: 'G-HX3CL1ET84',
  );
}
